apiVersion: v1
kind: PersistentVolumeClaim
metadata:  
  name: strapi-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp2
  volumeName: strapi-pv
