apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-strapi-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
  volumeMode: Filesystem
