apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-strapi-pv
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-08c8df41614fb6cf0
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mongo-strapi-data
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
